/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.2.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as bidhistories from "../bidhistories";
import type * as biditems from "../biditems";
import type * as chats from "../chats";
import type * as crons from "../crons";
import type * as http from "../http";
import type * as messages from "../messages";
import type * as notifications from "../notifications";
import type * as privatemessages from "../privatemessages";
import type * as stageitems from "../stageitems";
import type * as users from "../users";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  bidhistories: typeof bidhistories;
  biditems: typeof biditems;
  chats: typeof chats;
  crons: typeof crons;
  http: typeof http;
  messages: typeof messages;
  notifications: typeof notifications;
  privatemessages: typeof privatemessages;
  stageitems: typeof stageitems;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
